dataset:
  video_processor: Phoenix14TVideoProcessor
  bert_name: bert-base-german-dbmdz-uncased
  meta_processor: Phoenix14TNLGMetaProcessor
  train_path: data/phoenix14T/annotations/train.lst 
  val_path: data/phoenix14T/annotations/val.lst
  all_annotation: data/phoenix14T/annotations/all.pkl
  vfeat_dir: data/phoenix14T/features/all
  text_processor: NLGTextProcessor
  aligner: DSNLGAligner
  max_video_len: 32
  max_len: 96
fairseq:
  common:
    tensorboard_logdir: run
    log_interval: 1000
    fp16: true
  dataset:
    num_workers: 4
    batch_size: 32
  optimization:
    lr:
    - 5.0e-05
    clip_norm: 2.0
    optimizer: adam
    adam_betas: (0.9, 0.98)
    lr_scheduler: polynomial_decay
    total_num_update: 1000000
    warmup_updates: 122
    weight_decay: 0.0
    ddp_backend: no_c10d
    max_epoch: 100
  checkpoint:
    #restore_file: runs/vlm/how2sign_de/checkpoint_best.pt
    restore_file: runs/vlm/pre_phoenix14T/checkpoint_best.pt
    reset_optimizer: true
    reset_dataloader: true
    reset_meters: true
    keep_last_epochs: 10
    save_dir: runs/vlm/phoenix14T/pre_phoenix14T_ct
task_type: local_single
model:
  model_cls: MMFusionNLG
  mm_encoder_cls: MMBertForNLG
loss:
  loss_cls: NLGLoss
