dataset:
  video_processor: ShardedVideoProcessor
  bert_name: bert-base-german-dbmdz-uncased
  meta_processor: ShardedHow2MetaProcessor
  train_path: data/how2sign/annotations/train.lst
  val_path: data/how2sign/annotations/val.lst
  vfeat_dir: data/how2sign/features/s3d_shard_small
  text_processor: ShardedTextProcessor
  tfeat_dir: data/how2sign/features/s3d_shard_small_de/all_dedup_de.bert-base-german-dbmdz-uncased.
  aligner: MFMMLMAligner
  subsampling: 1
  sampled_min_len: 10
  sampled_max_len: 64
  max_video_len: 32
  max_len: 96
  lazy_vfeat_mask: true
  mfm_probability: 0.15
  mlm_probability: 0.15
  mm_prob: 0.5
fairseq:
  common:
    tensorboard_logdir: run
    log_interval: 1000
    fp16: true
  dataset:
    num_workers: 4
    batch_size: 16
  optimization:
    lr:
    - 5.0e-05
    clip_norm: 2.0
    optimizer: adam
    adam_betas: (0.9, 0.98)
    lr_scheduler: polynomial_decay
    total_num_update: 1000000
    warmup_updates: 1000
    weight_decay: 0.0
    ddp_backend: no_c10d
    max_epoch: 300
  checkpoint:
    save_dir: runs/mtm/vlm/how2sign_de/batch_size16
    save_interval_updates: 1024
    keep_interval_updates: 2
    keep_last_epochs: 30
task_type: local_big
slurm_config: big
eval:
  save_path: runs/mtm/vlm/how2sign_de/batch_size16
model:
  model_cls: MMFusionMTM
  mm_encoder_cls: MMBertForMFMMLM
loss:
  loss_cls: MTM
