includes: projects/task/test.yaml
dataset:
  split: test
  meta_processor: Phoenix14TNLGMetaProcessor
  test_path: data/phoenix14T/annotations/test.lst
  all_annotation: data/phoenix14T/annotations/all.pkl
  video_processor: Phoenix14TVideoProcessor
  vfeat_dir: data/phoenix14T/features/all
  text_processor: NLGTextProcessor
  aligner: DSNLGAligner
  max_video_len: 32
  max_len: 96
model:
  model_cls: MMFusionNLG
  mm_encoder_cls: MMBertForNLG
  max_decode_length: 24
  use_seg_emb: true
eval:
  #save_path: runs/mtm/vlm/phoenix14T/how2sign_de_eval
  #save_path: runs/mtm/vlm/pre_phoenix14T/eval
  save_path: runs/mtm/vlm/phoenix14T/pre_phoenix14T_ct/eval
fairseq:
  # read code and find what is the checkpoint arg.
  dataset:
    batch_size: 256
    valid_subset: test
    num_workers: 2
  common_eval:
    #path: runs/mtm/vlm/how2sign_de/checkpoint_best.pt
    #path: runs/mtm/vlm/pre_phoenix14T/checkpoint_best.pt
    path: runs/mtm/vlm/phoenix14T/pre_phoenix14T_ct/checkpoint_best.pt
metric: NLGMetric
predictor: NLGPredictor
gen_param:
  num_beams: 5
